# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bees_pb2 as bees__pb2


class BeesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckWord = channel.unary_unary(
                '/app.Bees/CheckWord',
                request_serializer=bees__pb2.InputWord.SerializeToString,
                response_deserializer=bees__pb2.WordInDict.FromString,
                )


class BeesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckWord': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckWord,
                    request_deserializer=bees__pb2.InputWord.FromString,
                    response_serializer=bees__pb2.WordInDict.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.Bees', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bees(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.Bees/CheckWord',
            bees__pb2.InputWord.SerializeToString,
            bees__pb2.WordInDict.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
